name: Dependabot slack notification

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  actions: write

defaults:
  run:
    shell: bash -euxo pipefail {0}

jobs:
  pr-slack-notification:
    runs-on: ubuntu-latest
    name: Debug Dependabot Slack

    steps:

      - name: Debug actor
        run: echo "Actor is ${{ github.actor }}"

      - name: Debug PR author
        run: echo "PR author is ${{ github.event.pull_request.user.login }}"

      - name: Debug labels
        run: echo "Labels ${{ toJson(github.event.pull_request.labels) }}"

      - name: Debug Slack channel ID
        run: echo "Channel ID is ${{ secrets.VAKGROEP_DEPENDABOT_SLACK_CHANNEL_ID }}"

      - name: Post PR summary message to Slack
        if: github.event.action == 'opened'
        id: message
        uses: slackapi/slack-github-action@v2.1.1
        with:
          method: chat.postMessage
          token: ${{ secrets.VAKGROEP_DEPENDABOT_SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.VAKGROEP_DEPENDABOT_SLACK_CHANNEL_ID }}
            username: "Bereikbaarheid Frontend"
            text: "DEBUG: PR #${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}"

      - name: Dump raw Slack response
        if: github.event.action == 'opened'
        run: echo '${{ steps.message.outputs.response }}'

      - name: Extract ts from Slack response
        if: github.event.action == 'opened'
        id: extract-ts
        run: |
          echo "Raw response:"
          echo '${{ steps.message.outputs.response }}'
          TS=$(echo '${{ steps.message.outputs.response }}' | jq -r '.ts')
          echo "Extracted TS: $TS"
          echo "ts=$TS" >> $GITHUB_OUTPUT

      - name: Post thread reply (DEBUG)
        if: github.event.action == 'opened'
        uses: slackapi/slack-github-action@v2.1.1
        with:
          method: chat.postMessage
          token: ${{ secrets.VAKGROEP_DEPENDABOT_SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.VAKGROEP_DEPENDABOT_SLACK_CHANNEL_ID }}
            thread_ts: "${{ steps.extract-ts.outputs.ts }}"
            text: "DEBUG THREAD MESSAGE"